spring:
#  H2
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/refsys
#    username: sa
#    password:

#  SQL Server
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

mybatis:
  mapper-locations: classpath:/repository/**/*.xml
  type-aliases-package: com.xray21.refsys.web.domain
  configuration:
    map-underscore-to-camel-case: true